[package]
name = "mgrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.4"
structopt = "0.3.26"
tokio = { version = "1.28.1", features = ["full"] }
